# Generated by Django 3.2 on 2021-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
