# Generated by Django 3.2 on 2021-06-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrive', '0002_auto_20210629_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
